# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66low/entities/account.proto\x12\rflow.entities\"\xce\x01\n\x07\x41\x63\x63ount\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x0c\x12\'\n\x04keys\x18\x04 \x03(\x0b\x32\x19.flow.entities.AccountKey\x12\x38\n\tcontracts\x18\x05 \x03(\x0b\x32%.flow.entities.Account.ContractsEntry\x1a\x30\n\x0e\x43ontractsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x8f\x01\n\nAccountKey\x12\r\n\x05index\x18\x01 \x01(\r\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x11\n\tsign_algo\x18\x03 \x01(\r\x12\x11\n\thash_algo\x18\x04 \x01(\r\x12\x0e\n\x06weight\x18\x05 \x01(\r\x12\x17\n\x0fsequence_number\x18\x06 \x01(\r\x12\x0f\n\x07revoked\x18\x07 \x01(\x08\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _ACCOUNT_CONTRACTSENTRY._options = None
  _ACCOUNT_CONTRACTSENTRY._serialized_options = b'8\001'
  _globals['_ACCOUNT']._serialized_start=47
  _globals['_ACCOUNT']._serialized_end=253
  _globals['_ACCOUNT_CONTRACTSENTRY']._serialized_start=205
  _globals['_ACCOUNT_CONTRACTSENTRY']._serialized_end=253
  _globals['_ACCOUNTKEY']._serialized_start=256
  _globals['_ACCOUNTKEY']._serialized_end=399
# @@protoc_insertion_point(module_scope)
