# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block_execution_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flow.entities import event_pb2 as flow_dot_entities_dot_event__pb2
from flow.entities import transaction_pb2 as flow_dot_entities_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(flow/entities/block_execution_data.proto\x12\rflow.entities\x1a\x19\x66low/entities/event.proto\x1a\x1f\x66low/entities/transaction.proto\"g\n\x12\x42lockExecutionData\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x0c\x12?\n\x14\x63hunk_execution_data\x18\x02 \x03(\x0b\x32!.flow.entities.ChunkExecutionData\"\xa5\x01\n\x12\x43hunkExecutionData\x12:\n\ncollection\x18\x01 \x01(\x0b\x32&.flow.entities.ExecutionDataCollection\x12$\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x14.flow.entities.Event\x12-\n\ntrieUpdate\x18\x03 \x01(\x0b\x32\x19.flow.entities.TrieUpdate\"K\n\x17\x45xecutionDataCollection\x12\x30\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1a.flow.entities.Transaction\"X\n\nTrieUpdate\x12\x11\n\troot_hash\x18\x01 \x01(\x0c\x12\r\n\x05paths\x18\x02 \x03(\x0c\x12(\n\x08payloads\x18\x03 \x03(\x0b\x32\x16.flow.entities.Payload\"A\n\x07Payload\x12\'\n\x07keyPart\x18\x01 \x03(\x0b\x32\x16.flow.entities.KeyPart\x12\r\n\x05value\x18\x02 \x01(\x0c\"&\n\x07KeyPart\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x0c\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.block_execution_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_BLOCKEXECUTIONDATA']._serialized_start=119
  _globals['_BLOCKEXECUTIONDATA']._serialized_end=222
  _globals['_CHUNKEXECUTIONDATA']._serialized_start=225
  _globals['_CHUNKEXECUTIONDATA']._serialized_end=390
  _globals['_EXECUTIONDATACOLLECTION']._serialized_start=392
  _globals['_EXECUTIONDATACOLLECTION']._serialized_end=467
  _globals['_TRIEUPDATE']._serialized_start=469
  _globals['_TRIEUPDATE']._serialized_end=557
  _globals['_PAYLOAD']._serialized_start=559
  _globals['_PAYLOAD']._serialized_end=624
  _globals['_KEYPART']._serialized_start=626
  _globals['_KEYPART']._serialized_end=664
# @@protoc_insertion_point(module_scope)
