# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from flow.entities import collection_pb2 as flow_dot_entities_dot_collection__pb2
from flow.entities import block_seal_pb2 as flow_dot_entities_dot_block__seal__pb2
from flow.entities import execution_result_pb2 as flow_dot_entities_dot_execution__result__pb2
from flow.entities import block_header_pb2 as flow_dot_entities_dot_block__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66low/entities/block.proto\x12\rflow.entities\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1e\x66low/entities/collection.proto\x1a\x1e\x66low/entities/block_seal.proto\x1a$flow/entities/execution_result.proto\x1a flow/entities/block_header.proto\"\xa5\x03\n\x05\x42lock\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x11\n\tparent_id\x18\x02 \x01(\x0c\x12\x0e\n\x06height\x18\x03 \x01(\x04\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x41\n\x15\x63ollection_guarantees\x18\x05 \x03(\x0b\x32\".flow.entities.CollectionGuarantee\x12-\n\x0b\x62lock_seals\x18\x06 \x03(\x0b\x32\x18.flow.entities.BlockSeal\x12\x12\n\nsignatures\x18\x07 \x03(\x0c\x12G\n\x1a\x65xecution_receipt_metaList\x18\x08 \x03(\x0b\x32#.flow.entities.ExecutionReceiptMeta\x12=\n\x15\x65xecution_result_list\x18\t \x03(\x0b\x32\x1e.flow.entities.ExecutionResult\x12\x30\n\x0c\x62lock_header\x18\n \x01(\x0b\x32\x1a.flow.entities.BlockHeader*G\n\x0b\x42lockStatus\x12\x11\n\rBLOCK_UNKNOWN\x10\x00\x12\x13\n\x0f\x42LOCK_FINALIZED\x10\x01\x12\x10\n\x0c\x42LOCK_SEALED\x10\x02\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.block_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_BLOCKSTATUS']._serialized_start=637
  _globals['_BLOCKSTATUS']._serialized_end=708
  _globals['_BLOCK']._serialized_start=214
  _globals['_BLOCK']._serialized_end=635
# @@protoc_insertion_point(module_scope)
