# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block_seal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66low/entities/block_seal.proto\x12\rflow.entities\"\xf3\x01\n\tBlockSeal\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x0c\x12\x1c\n\x14\x65xecution_receipt_id\x18\x02 \x01(\x0c\x12$\n\x1c\x65xecution_receipt_signatures\x18\x03 \x03(\x0c\x12\"\n\x1aresult_approval_signatures\x18\x04 \x03(\x0c\x12\x13\n\x0b\x66inal_state\x18\x05 \x01(\x0c\x12\x11\n\tresult_id\x18\x06 \x01(\x0c\x12\x44\n\x18\x61ggregated_approval_sigs\x18\x07 \x03(\x0b\x32\".flow.entities.AggregatedSignature\"F\n\x13\x41ggregatedSignature\x12\x1b\n\x13verifier_signatures\x18\x01 \x03(\x0c\x12\x12\n\nsigner_ids\x18\x02 \x03(\x0c\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.block_seal_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_BLOCKSEAL']._serialized_start=50
  _globals['_BLOCKSEAL']._serialized_end=293
  _globals['_AGGREGATEDSIGNATURE']._serialized_start=295
  _globals['_AGGREGATEDSIGNATURE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
