# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/collection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66low/entities/collection.proto\x12\rflow.entities\"1\n\nCollection\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x17\n\x0ftransaction_ids\x18\x02 \x03(\x0c\"\x9b\x01\n\x13\x43ollectionGuarantee\x12\x15\n\rcollection_id\x18\x01 \x01(\x0c\x12\x12\n\nsignatures\x18\x02 \x03(\x0c\x12\x1a\n\x12reference_block_id\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x12\n\nsigner_ids\x18\x05 \x03(\x0c\x12\x16\n\x0esigner_indices\x18\x06 \x01(\x0c\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.collection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_COLLECTION']._serialized_start=49
  _globals['_COLLECTION']._serialized_end=98
  _globals['_COLLECTIONGUARANTEE']._serialized_start=101
  _globals['_COLLECTIONGUARANTEE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
