# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66low/entities/event.proto\x12\rflow.entities\"n\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x0c\x12\x19\n\x11transaction_index\x18\x03 \x01(\r\x12\x13\n\x0b\x65vent_index\x18\x04 \x01(\r\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_EVENT']._serialized_start=44
  _globals['_EVENT']._serialized_end=154
# @@protoc_insertion_point(module_scope)
