# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/node_version_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%flow/entities/node_version_info.proto\x12\rflow.entities\"]\n\x0fNodeVersionInfo\x12\x0e\n\x06semver\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\t\x12\x10\n\x08spork_id\x18\x03 \x01(\x0c\x12\x18\n\x10protocol_version\x18\x04 \x01(\x04\x42P\n\x1corg.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow.entities.node_version_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034org.onflow.protobuf.entitiesZ0github.com/onflow/flow/protobuf/go/flow/entities'
  _globals['_NODEVERSIONINFO']._serialized_start=56
  _globals['_NODEVERSIONINFO']._serialized_end=149
# @@protoc_insertion_point(module_scope)
